name: "Label MC Version PRs"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "serenibyss/TestCI"
    - uses: actions/labeler@v5
