name: Mention upstream repo for new pull requests

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    uses: serenibyss/TestCI/.github/workflows/upstream_commentor_ref.yml@main
    secrets: inherit
    with:
      upstream: 'https://www.google.com'
      auto_close: true
